services:
  - type: web
    name: nba-team-analysis-reporting-platform
    env: docker
    autoDeploy: true
    healthCheckPath: /healthz
    envVars:
      - key: FLASK_SECRET_KEY
        generateValue: true
      - key: LOG_LEVEL
        value: INFO
      - key: NBA_API_TIMEOUT
        value: "90"
      - key: NBA_API_RETRIES
        value: "5"
      - key: NBA_API_BACKOFF_BASE
        value: "2.5"
      - key: NBA_API_USE_CACHE_ON_FAILURE
        value: "1"
      - key: WARM_CACHE_ON_START
        value: "0"
      - key: WARM_TEAM_ABBRS
        value: "GSW"
      - key: GUNICORN_WORKERS
        value: "2"
      - key: GUNICORN_THREADS
        value: "4"
      - key: GUNICORN_TIMEOUT
        value: "120"
